Repository nextcloud/social, pull requests merged in 2018-12, with the labels that each got.

#143 replace rightJoin -> join
  lib/Controller/LocalController.php
  lib/Cron/Queue.php
  lib/Db/CoreRequestBuilder.php
  lib/Db/FollowsRequest.php
  lib/Db/NotesRequest.php
  lib/Db/NotesRequestBuilder.php
  lib/Service/ActivityPub/NoteService.php
Labels: 3. to review, bug

#146 Some tools to publish
  Makefile
Labels: 3. to review, enhancement

#156 Add issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/pull_request_template.md
Labels: 3. to review

#169 Run well-known check after setup
  lib/Controller/NavigationController.php
Labels: 3. to review, bug

#198 malformed call
  lib/Service/ImportService.php
Labels: 3. to review, bug, good first issue

#185 removing useless getLastInsertId()
  lib/Db/CacheActorsRequest.php
  lib/Db/NotesRequest.php
Labels: 3. to review, technical debt

#194 Bigger field to store data source for notes and actors cache
  lib/Db/CacheActorsRequest.php
  lib/Db/CoreRequestBuilder.php
  lib/Db/NotesRequest.php
  lib/Migration/Version0001Date20181208185242.php
Labels: 3. to review, bug, enhancement

#216 include the getAccount within the try/catch
  lib/Service/ActorService.php
Labels: 3. to review

#177 Async the process only if there is request in STANDBY
  lib/Controller/QueueController.php
Labels: 3. to review, enhancement

#178 detect ghost account and avoid them
  lib/Service/ActorService.php
Labels: 3. to review, bug

#241 Add app compatibility check and php syntax checks
  .drone.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review

#184 check installation on upgrade or account creation
  appinfo/info.xml
  composer.lock
  lib/Controller/NavigationController.php
  lib/Db/FollowsRequest.php
  lib/Migration/CheckInstallation.php
  lib/Service/CheckService.php
Labels: 4. to release, bug

#179 Display on to:PUBLIC message
  lib/Db/NotesRequest.php
  lib/Db/NotesRequestBuilder.php
Labels: 4. to release, bug

#197 do not search for followers Id within the attributed_to field
  lib/Db/NotesRequestBuilder.php
Labels: 4. to release, enhancement

#242 reordering background-jobs
  appinfo/info.xml
Labels: 4. to release

#196 Some data are only for internal use.
  lib/Model/ActivityPub/Activity/Accept.php
  lib/Model/ActivityPub/Activity/Create.php
  lib/Model/ActivityPub/Activity/Delete.php
  lib/Model/ActivityPub/Activity/Reject.php
  lib/Model/ActivityPub/Activity/Undo.php
  lib/Model/ActivityPub/Follow.php
  lib/Model/ActivityPub/Image.php
  lib/Model/ActivityPub/Tombstone.php
Labels: 4. to release, enhancement

#176 Cleaning some TODO
  lib/Controller/AccountController.php
  lib/Controller/ActivityPubController.php
  lib/Controller/LocalController.php
  lib/Controller/NavigationController.php
  lib/Controller/QueueController.php
  lib/Model/ActivityPub/ACore.php
  lib/Service/ActivityPub/FollowService.php
  lib/Service/CacheService.php
Labels: 3. to review, enhancement

#181 adding route and content to the Notification Stream
  appinfo/routes.php
  lib/Controller/LocalController.php
  lib/Db/NotesRequest.php
  lib/Service/ActivityPub/NoteService.php
Labels: 3. to review, enhancement

#195 Unfollow will send a request to remote instance
  lib/Service/ActivityPub/FollowService.php
Labels: 3. to review, enhancement

#206 linked data signature
  composer.json
  composer.lock
  lib/Controller/ActivityPubController.php
  lib/Db/NotesRequest.php
  lib/Exceptions/LinkedDataSignatureMissingException.php
  lib/Model/ActivityPub/ACore.php
  lib/Model/ActivityPub/Note.php
  lib/Model/LinkedDataSignature.php
  lib/Service/ActivityPub/NoteService.php
  lib/Service/ActivityService.php
  lib/Service/ImportService.php
Labels: 3. to review, enhancement

#246 Fix composer layout on longer messages
  package-lock.json
  package.json
  src/components/Composer.vue
  webpack.common.js
Labels: 3. to review, bug, design

#249 Cleaning: unused import and composer lib
  composer.lock
  lib/Command/QueueProcess.php
  lib/Controller/ActivityPubController.php
  lib/Cron/Queue.php
  lib/Db/NotesRequest.php
  lib/Model/ActivityPub/ACore.php
  lib/Model/ActivityPub/Object/Document.php
  lib/Model/ActivityPub/Object/Image.php
  lib/Service/ActivityService.php
  lib/Service/SignatureService.php
Labels: 3. to review

#244 Public page frontend fixes
  appinfo/routes.php
  lib/Controller/AccountController.php
  lib/Controller/LocalController.php
  lib/Controller/SocialPubController.php
  src/App.vue
  src/components/ProfileInfo.vue
  src/components/UserEntry.vue
  src/router.js
  src/store/account.js
  src/views/Profile.vue
Labels: 3. to review, bug

#251 signed header generation moved to SignatureService
  lib/Model/ActivityPub/Object/Note.php
  lib/Service/ActivityService.php
  lib/Service/SignatureService.php
Labels: 3. to review

#252 ./occ social:reset
  appinfo/info.xml
  lib/Command/Reset.php
  lib/Db/CoreRequestBuilder.php
Labels: 3. to review, enhancement

#254 +strtolower()
  lib/Service/CurlService.php
Labels: 3. to review

#217 varchar->text
  lib/Db/CacheActorsRequest.php
  lib/Db/CoreRequestBuilder.php
  lib/Db/NotesRequest.php
  lib/Migration/Version0001Date20181204203147.php
  lib/Migration/Version0001Date20181219000001.php
  lib/Migration/Version0001Date20181219000002.php
  lib/Migration/Version0001Date20181219000003.php
  lib/Migration/Version0001Date20181219000004.php
Labels: 3. to review, bug

#256 checking origin of the object
  lib/Interfaces/Activity/FollowInterface.php
  lib/Interfaces/Activity/UndoInterface.php
  lib/Interfaces/Actor/PersonInterface.php
  lib/Interfaces/Object/NoteInterface.php
  lib/Service/ImportService.php
Labels: 3. to review

#263 Only send one search request at a time to the server
  src/components/Search.vue
Labels: 3. to review, bug

#261 adding NoCSRFRequired to globalActorAvatar
  lib/Controller/LocalController.php
Labels: 3. to review

#255 htmlentities encode/decode
  lib/Db/NotesRequestBuilder.php
  lib/Model/ActivityPub/ACore.php
  lib/Model/ActivityPub/Actor/Person.php
  lib/Model/ActivityPub/Object/Note.php
  lib/Service/PostService.php
Labels: 3. to review, enhancement

#262 0.1.1
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review, 4. to release

#266 document "occ social:reset" in readme
  README.md
Labels: 3. to review, enhancement
