Repository nextcloud/social, pull requests merged in 2019-07, with the labels that each got.

#620 Fixes the overlap of the tooltip and the popover menu in TimeLinePost
  src/components/TimelinePost.vue
Labels: 4. to release, bug

#621 [WIP] Add a like button
  lib/Controller/LocalController.php
  lib/Service/LikeService.php
  src/components/TimelinePost.vue
  src/store/timeline.js
Labels: 4. to release, enhancement

#636 Cut unnecessary info from readme
  README.md
Labels: 3. to review, enhancement
