Repository nextcloud/social, pull requests merged in 2019-01, with the labels that each got.

#290 compare Accept Header from a list
  lib/Controller/ActivityPubController.php
Labels: 3. to review

#280 get item by Id and delete it
  lib/Interfaces/Activity/DeleteInterface.php
  lib/Interfaces/Actor/PersonInterface.php
  lib/Interfaces/IActivityPubInterface.php
  lib/Interfaces/Object/NoteInterface.php
Labels: 3. to review, enhancement

#279 switch to getInsecureServerHost
  lib/Service/SignatureService.php
Labels: 3. to review

#275 check if there is standby request related to token
  lib/Service/ActivityService.php
Labels: 3. to review

#283 [huge] rewrite of the exceptions while requesting remote instance
  composer.lock
  lib/AP.php
  lib/Command/QueueProcess.php
  lib/Controller/ActivityPubController.php
  lib/Controller/QueueController.php
  lib/Controller/SocialPubController.php
  lib/Cron/Queue.php
  lib/Db/CacheDocumentsRequest.php
  lib/Db/RequestQueueRequest.php
  lib/Exceptions/CacheContentSizeException.php
  lib/Exceptions/ItemUnknownException.php
  lib/Exceptions/Request410Exception.php
  lib/Exceptions/RequestContentException.php
  lib/Exceptions/RequestException.php
  lib/Exceptions/RequestNetworkException.php
  lib/Exceptions/RequestResultSizeException.php
  lib/Exceptions/RequestServerException.php
  lib/Exceptions/RetrieveAccountFormatException.php
  lib/Exceptions/ServiceAccountAlreadyExistException.php
  lib/Exceptions/UnknownItemException.php
  lib/Exceptions/WebfingerException.php
  lib/Interfaces/Activity/AcceptInterface.php
  lib/Interfaces/Activity/AddInterface.php
  lib/Interfaces/Activity/BlockInterface.php
  lib/Interfaces/Activity/CreateInterface.php
  lib/Interfaces/Activity/DeleteInterface.php
  lib/Interfaces/Activity/FollowInterface.php
  lib/Interfaces/Activity/LikeInterface.php
  lib/Interfaces/Activity/RejectInterface.php
  lib/Interfaces/Activity/RemoveInterface.php
  lib/Interfaces/Activity/UndoInterface.php
  lib/Interfaces/Activity/UpdateInterface.php
  lib/Model/ActivityPub/Actor/Person.php
  lib/Model/ActivityPub/Object/Image.php
  lib/Service/ActivityService.php
  lib/Service/CacheActorService.php
  lib/Service/CacheDocumentService.php
  lib/Service/ConfigService.php
  lib/Service/CurlService.php
  lib/Service/DocumentService.php
  lib/Service/FollowService.php
  lib/Service/ImportService.php
  lib/Service/NoteService.php
  lib/Service/QueueService.php
  lib/Service/SignatureService.php
Labels: 3. to review

#274 Using signature date as 'creation' date
  lib/Controller/ActivityPubController.php
  lib/Db/CacheActorsRequest.php
  lib/Interfaces/Actor/PersonInterface.php
  lib/Model/ActivityPub/Item.php
  lib/Service/SignatureService.php
Labels: 3. to review

#292 0.1.2 - changelog and appinfo
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 2. developing, 3. to review

#300 There is no use to check twice
  lib/Model/ActivityPub/Object/Note.php
  lib/Service/ActivityService.php
  lib/Service/SignatureService.php
Labels: 3. to review

#304 Compat friendica
  composer.json
  composer.lock
  lib/Migration/Version0001Date20190103000001.php
  lib/Migration/Version0001Date20190103000002.php
  lib/Migration/Version0001Date20190103000003.php
  lib/Migration/Version0001Date20190103000004.php
  lib/Model/LinkedDataSignature.php
Labels: 3. to review

#313 check address of the account
  .drone.yml
  lib/webfinger.php
Labels: 4. to release, backport-request

#298 Properly return promise when creating a new post
  src/store/timeline.js
Labels: 3. to review, backport-request, bug

#326 Always use @ infront of account id
  src/components/ProfileInfo.vue
  src/components/TimelineEntry.vue
  src/router.js
Labels: 3. to review, backport-request, bug

#334 signature can be 5min old
  lib/Service/SignatureService.php
Labels: 3. to review, backport-request

#341 instructions about Emojis
  README.md
Labels: 3. to review

#342 Provide more details in logs on fail to async
  lib/Service/CurlService.php
Labels: 3. to review, backport-request

#344 Failed to load more timeline entries
  lib/Service/CacheActorService.php
Labels: backport-request

#336 throw RequestResultNotJsonException on unusual result
  lib/Controller/SocialPubController.php
  lib/Db/NotesRequestBuilder.php
  lib/Exceptions/RequestResultNotJsonException.php
  lib/Interfaces/Activity/DeleteInterface.php
  lib/Interfaces/Activity/FollowInterface.php
  lib/Interfaces/Object/NoteInterface.php
  lib/Service/AccountService.php
  lib/Service/ActivityService.php
  lib/Service/CacheActorService.php
  lib/Service/CacheDocumentService.php
  lib/Service/CurlService.php
  lib/Service/DocumentService.php
  lib/Service/FollowService.php
  lib/Service/NoteService.php
  lib/Service/SignatureService.php
Labels: 3. to review

#335 add w3 @context in actor
  lib/Controller/ActivityPubController.php
  lib/Model/ActivityPub/ACore.php
Labels: 3. to review, backport-request

#340 Refresh some Actor details in cache on Follow events
  lib/Command/CacheRefresh.php
  lib/Command/NoteCreate.php
  lib/Controller/LocalController.php
  lib/Db/CacheActorsRequest.php
  lib/Interfaces/Activity/FollowInterface.php
  lib/Model/Post.php
  lib/Service/AccountService.php
  lib/Service/ActivityService.php
  lib/Service/ActorService.php
  lib/Service/NoteService.php
  lib/Service/PostService.php
Labels: 3. to review, backport-request

#353 0.1.3
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: backport-request

#361 Use more recent node version for js building
  .drone.yml
Labels: 3. to review, backport-request, bug

#364 0.2.0-dev01
  Makefile
  appinfo/info.xml
Labels: 3. to review

#367 Adjust part about other platforms to find friends on, fix #329
  README.md
Labels: 3. to review, enhancement
