Repository nextcloud/social, pull requests merged in 2019-02, with the labels that each got.

#386 allow FOLLOWLOCATION
  lib/Service/CurlService.php
Labels: 4. to release, backport-request, enhancement

#388 custom apps folder and webfinger
  lib/Service/ConfigService.php
  lib/webfinger.php
Labels: 3. to review, backport-request

#398 Use chunkhash to properly trigger reload of webpack chunks on upgrade
  webpack.common.js
Labels: 3. to review, backport-request, bug

#405 Issue with ./occ social:cache:refresh
  lib/Command/CacheRefresh.php
Labels: 3. to review

#403 removing js/
  Makefile
Labels: 3. to review, backport-request

#402 0.1.4
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review

#415 call uuid() froom TStringTools;
  lib/Interfaces/Actor/PersonInterface.php
  lib/Model/ActivityPub/ACore.php
  lib/Model/RequestQueue.php
  lib/Service/CacheDocumentService.php
Labels: 3. to review

#314 Add the ability to follow from external website
  appinfo/routes.php
  lib/Controller/OStatusController.php
  lib/Service/AccountService.php
  lib/Service/CurlService.php
  lib/webfinger.php
  src/components/ProfileInfo.vue
  src/ostatus.js
  src/views/OStatus.vue
  templates/ostatus.php
  webpack.common.js
Labels: 3. to review

#412 Delete on Actor delete also Note from this Actor
  lib/Db/NotesRequest.php
  lib/Interfaces/Activity/DeleteInterface.php
  lib/Interfaces/Actor/PersonInterface.php
Labels: 3. to review

#323 Add UI to reply to a post and delete
  css/style.css
  css/style.scss
  img/reply.svg
  src/components/ActorAvatar.vue
  src/components/Composer.vue
  src/components/TimelineEntry.vue
  src/components/TimelineList.vue
  src/main.js
  src/mixins/popoverMenu.js
  src/store/timeline.js
Labels: 3. to review, enhancement

#433 create object even if it can't be signed
  context/w3id.org.identity.v1.json
  context/w3id.org.security.v1.json
  context/www.w3.org.ns.activitystreams.json
  lib/Model/LinkedDataSignature.php
  lib/Service/SignatureService.php
Labels: 3. to review, backport-request
