Repository nextcloud/social, pull requests merged in 2019-03, with the labels that each got.

#445 use mixin to invert emoji picker icon in dark theme
  css/style.scss
  img/emoji.svg
  src/components/Composer.vue
  src/main.js
Labels: 4. to release, backport-request, bug

#439 Enlarge some fields
  lib/Migration/Version0002Date20190226000001.php
  lib/Migration/Version0002Date20190226000002.php
  lib/Migration/Version0002Date20190226000003.php
  lib/Migration/Version0002Date20190226000004.php
Labels: 3. to review

#455 force large field to 1000
  lib/Migration/Version0002Date20190226000001.php
Labels: 3. to review

#454 Add basic test skeleton
  .drone.yml
  composer.json
  composer.lock
  tests/SocialTest.php
  tests/bootstrap.php
  tests/drone-server-install.sh
  tests/drone-server-setup.sh
  tests/phpunit.xml
Labels: 3. to review

#453 creating a new field id_prim, set as primary and fill it
  lib/Db/ActorsRequest.php
  lib/Db/CacheActorsRequest.php
  lib/Db/CacheDocumentsRequest.php
  lib/Db/CoreRequestBuilder.php
  lib/Db/FollowsRequest.php
  lib/Db/NotesRequest.php
  lib/Migration/Version0002Date20190305091901.php
  lib/Migration/Version0002Date20190305091902.php
Labels: 3. to review

#463 reorder post privacy to be consistent with mastodon
  src/components/Composer.vue
Labels: 3. to review, design, enhancement

#472 Delete .travis.yml
  .travis.yml
Labels: 3. to review
