Repository nextcloud/social, pull requests merged in 2020-10, with the labels that each got.

#1043 fix well-known autoloader paths
  lib/hostmeta.php
  lib/webfinger.php
Labels: 3. to review

#243 Add cypress testing
  .github/workflows/cypress.yml
  .gitignore
  cypress.json
  cypress/docker-compose.yml
  cypress/initserver.sh
  cypress/integration/0.setup.spec.js
  cypress/integration/post.spec.js
  cypress/plugins/index.js
  cypress/start.sh
  cypress/stop.sh
  cypress/support/commands.js
  cypress/support/index.js
  cypress/utils/index.js
  lib/Migration/Version0003Date20200611000001.php
  package-lock.json
  package.json
Labels: 3. to review

#1050 Fix documentation link going to outdated version
  src/App.vue
Labels: 3. to review, enhancement

#1035 render messages based on the source html
  package.json
  src/components/Emoji.vue
  src/components/MessageContent.js
  src/components/TimelinePost.vue
  src/router.js
Labels: 2. developing

#1052 use default composer vendor directory
  .drone.yml
  .gitignore
  composer.json
  lib/AppInfo/Application.php
  lib/hostmeta.php
  lib/webfinger.php
  tests/bootstrap.php
Labels: 3. to review

#1053 cypress fixes
  cypress/integration/0.setup.spec.js
  cypress/integration/post.spec.js
  cypress/support/commands.js
Labels: 3. to review

#1054 show all activity when viewing your own profile, not just public acti…
  lib/Db/SocialLimitsQueryBuilder.php
  lib/Db/StreamRequest.php
Labels: 3. to review

#1055 migrate away from depricated OC.generateUrl
  package-lock.json
  package.json
  src/App.vue
  src/components/ActorAvatar.vue
  src/components/Composer.vue
  src/components/MessageContent.js
  src/components/PostAttachment.vue
  src/components/ProfileInfo.vue
  src/components/Search.vue
  src/components/TimelinePost.vue
  src/components/UserEntry.vue
  src/mixins/follow.js
  src/router.js
  src/store/account.js
  src/store/timeline.js
  src/views/OStatus.vue
Labels: 3. to review

#1069 use prefered username as fallback if no account name is provided
  src/components/ProfileInfo.vue
Labels: 3. to review

#1073 fix unfollow
  lib/Model/ActivityPub/Object/Follow.php
Labels: 3. to review

#1076 remove empty content after a post has been added
  cypress/integration/post.spec.js
  src/components/TimelineList.vue
Labels: 3. to review

#748 👌 IMPROVE: move timeline to css grid layout and restructure code
  appinfo/routes.php
  src/components/MessageContent.js
  src/components/TimelineAvatar.vue
  src/components/TimelineEntry.vue
  src/components/TimelinePost.vue
  webpack.common.js
Labels: 3. to review, design, enhancement
