Repository nextcloud/social, pull requests merged in 2020-09, with the labels that each got.

#986 query instead of create Application in background jobs
  lib/Cron/Cache.php
  lib/Cron/Chunk.php
  lib/Cron/Queue.php
Labels: 3. to review

#984 switch from vue-style-loader to style-loader
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review

#994 👌 IMPROVE: use vue Content components and transmit serverData over initialState
  lib/Controller/NavigationController.php
  lib/Controller/OStatusController.php
  lib/Controller/SocialPubController.php
  package.json
  src/App.vue
  src/main.js
  src/ostatus.js
  src/views/OStatus.vue
  src/views/TimelineSinglePost.vue
  templates/main.php
  templates/ostatus.php
  templates/stream.php
Labels: 3. to review

#1028 preserve some of the whitespace from html tags
  lib/Model/ActivityPub/ACore.php
Labels: 3. to review, bug

#1027 render profile page for ostatus follow url
  lib/Controller/OStatusController.php
  src/router.js
  src/views/Profile.vue
Labels: 3. to review, bug

#1033 Move wiki pages to docs folder
  docs/3rd-party-fediverse-clients.md
  docs/List-of-occ-commands.md
  docs/Testing-the-API.md
Labels: 3. to review, enhancement

#1032 fix migration by allowing null values for 'nid'
  lib/Migration/Version0003Date20200823023911.php
Labels: 3. to review
