Repository nextcloud/social, pull requests merged in 2022-11, with the labels that each got.

#1506 returns 404 on missing Actor
  lib/WellKnown/JrdResponse.php
  lib/WellKnown/WebfingerHandler.php
Labels: 3. to review

#1507 fix publicKey
  lib/Model/LinkedDataSignature.php
Labels: 3. to review

#1493 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1521 confirmation popup
  appinfo/routes.php
  lib/Controller/OAuthController.php
  src/oauth.js
  src/views/OAuth2Authorize.vue
  templates/oauth2.php
  webpack.common.js
Labels: 1. to develop, 3. to review

#1517 status creation from mastodon client
  appinfo/routes.php
  composer.lock
  lib/Command/Fediverse.php
  lib/Command/MigrateAlpha3.php
  lib/Command/NoteCreate.php
  lib/Command/QueueStatus.php
  lib/Command/Timeline.php
  lib/Controller/ApiController.php
  lib/Controller/OAuthController.php
  lib/Db/ActorsRequest.php
  lib/Db/ActorsRequestBuilder.php
  lib/Db/CacheActorsRequest.php
  lib/Db/ClientRequest.php
  lib/Db/CoreRequestBuilder.php
  lib/Db/RequestQueueRequest.php
  lib/Db/SocialCrossQueryBuilder.php
  lib/Db/SocialLimitsQueryBuilder.php
  lib/Db/StreamActionsRequest.php
  lib/Db/StreamQueueRequest.php
  lib/Db/StreamRequest.php
  lib/Db/StreamRequestBuilder.php
  lib/Migration/Version1000Date20221118000001.php
  lib/Model/Client/Options/TimelineOptions.php
  lib/Model/Client/Status.php
  lib/Service/PostService.php
  lib/Service/StreamService.php
  lib/Tools/Traits/TNCLogger.php
Labels: 3. to review
