Repository nextcloud/social, pull requests merged in 2022-06, with the labels that each got.

#1426 add readme to undraw folder
  .reuse/dep5
  img/undraw/readme.md
Labels: enhancement, 4. to release

#1429 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1432 Improve posts rendering
  src/components/TimelineAvatar.vue
  src/components/TimelineEntry.vue
  src/components/TimelinePost.vue
Labels: 3. to review
