Repository nextcloud/social, pull requests merged in 2023-01, with the labels that each got.

#1562 Fix detection of webfinger endpoint with no 'resource' param
  lib/WellKnown/WebfingerHandler.php
Labels: bug, 3. to review, php

#1558 Make CI green
  .github/workflows/cypress.yml
  cypress.config.js
  cypress.json
  cypress/docker-compose.yml
  cypress/e2e/0.setup.cy.js
  cypress/e2e/post.cy.js
  cypress/initserver.sh
  cypress/plugins/index.js
  cypress/start.sh
  cypress/support/commands.js
  cypress/support/e2e.js
  lib/AP.php
  lib/Controller/ActivityPubController.php
  lib/Listeners/ProfileSectionListener.php
  lib/Model/ActivityPub/ACore.php
  lib/Model/Instance.php
  lib/Model/RequestQueue.php
  lib/Search/UnifiedSearchProvider.php
  lib/Service/CacheActorService.php
  lib/Service/CacheDocumentService.php
  lib/Service/ConfigService.php
  lib/Service/CurlService.php
  lib/Service/FollowService.php
  lib/Service/HashtagService.php
  lib/Service/MiscService.php
  lib/Service/PostService.php
  lib/Service/SearchService.php
  lib/Service/SignatureService.php
  lib/Service/StreamService.php
  lib/Tools/Model/Request.php
  lib/Tools/Traits/TNCLogger.php
  package-lock.json
  package.json
  src/components/Composer/Composer.vue
  src/components/TimelinePost.vue
  tests/psalm-baseline.xml
Labels: bug, 3. to review, dependencies, javascript

#1564 cast string to header
  lib/Service/CacheActorService.php
  lib/Service/SignatureService.php
Labels: 3. to review

#1565 ignore exception on unknown account during search
  lib/Db/CacheActorsRequest.php
  lib/Service/SearchService.php
Labels: 3. to review

#1566 delete actor on 410
  lib/Db/CacheActorsRequest.php
  lib/Interfaces/Actor/PersonInterface.php
  lib/Service/AccountService.php
  lib/Service/CacheActorService.php
  lib/Service/CurlService.php
Labels: 3. to review

#1570 Revert removal of MessageContent
  .github/workflows/cypress.yml
  src/components/MessageContent.js
  src/components/TimelinePost.vue
Labels: bug, 3. to review, javascript

#1571 Fixes on user profile
  src/components/FollowButton.vue
  src/components/ProfileInfo.vue
  src/store/account.js
Labels: bug, 3. to review, javascript

#1572 Improve rendering of user entry in user lists
  src/components/UserEntry.vue
Labels: bug, 3. to review, javascript

#1574 Check webfinger after having created the user
  lib/Controller/NavigationController.php
Labels: bug, 3. to review, php

#1580 Add ES and style lint workflows
  .eslintrc.js
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  package-lock.json
  package.json
  src/components/Composer/Composer.vue
  src/components/Emoji.vue
  src/components/MessageContent.js
  src/components/TimelineList.vue
  src/components/TimelinePost.vue
  src/directives/focusOnCreate.js
  src/main.js
  src/mixins/accountMixins.js
  src/mixins/serverData.js
  src/oauth.js
  src/router.js
  src/store/account.js
  src/store/index.js
  src/store/settings.js
  src/store/timeline.js
  src/views/OAuth2Authorize.vue
  src/views/OStatus.vue
  src/views/ProfileFollowers.vue
  src/views/ProfileTimeline.vue
  src/views/Timeline.vue
  src/views/TimelineSinglePost.vue
  stylelint.config.js
Labels: 3. to review, technical debt, javascript

#1581 Use new timeline API
  appinfo/routes.php
  lib/Controller/ApiController.php
  src/store/timeline.js
Labels: enhancement, 3. to review, javascript, front-end, backend, php

#1587 Revert "Merge pull request #1581 from nextcloud/artonge/feat/use_new_api"
  src/store/timeline.js
Labels: bug, 3. to review, javascript

#1588 Fix posting attachments
  lib/Controller/LocalController.php
  src/components/Composer/Composer.vue
  src/components/PostAttachment.vue
  src/components/TimelineEntry.vue
  src/components/TimelinePost.vue
Labels: bug, 3. to review, javascript, front-end

#1593 0.6.0-beta1
  Makefile
  appinfo/info.xml
  composer.lock
Labels: 4. to release
