Repository nextcloud/social, pull requests merged in 2023-06, with the labels that each got.

#1779 update details only
  lib/Service/AccountService.php
  lib/Service/ActorService.php
Labels: backport-request

#1795 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#1748 Modernize e2e tests
  .github/workflows/cypress.yml
  appinfo/info.xml
  composer.json
  composer.lock
  cypress.config.js
  cypress.config.ts
  cypress/.eslintrc.js
  cypress/docker-compose.yml
  cypress/dockerNode.ts
  cypress/e2e/0.setup.cy.js
  cypress/e2e/post.cy.js
  cypress/e2e/post.cy.ts
  cypress/e2e/setup.cy.ts
  cypress/initserver.sh
  cypress/start.sh
  cypress/stop.sh
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  cypress/utils/index.ts
  lib/Db/CoreRequestBuilder.php
  lib/Db/RequestQueueRequest.php
  lib/Db/StreamRequestBuilder.php
  lib/Model/Client/SocialClient.php
  lib/Service/CurlService.php
  lib/Service/FediverseService.php
  lib/Service/PushService.php
  lib/Tools/Db/ExtendedQueryBuilder.php
  lib/WellKnown/WebfingerHandler.php
  package-lock.json
  package.json
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review
