Repository nextcloud/social, pull requests merged in 2023-03, with the labels that each got.

#1615 Use new API for attachments posts
  .babelrc.js
  css/style.scss
  lib/Controller/ApiController.php
  lib/Controller/LocalController.php
  lib/Db/StreamRequest.php
  lib/Model/ActivityPub/Stream.php
  package-lock.json
  package.json
  src/App.vue
  src/components/ActorAvatar.vue
  src/components/Composer/Composer.vue
  src/components/Composer/PreviewGrid.vue
  src/components/Composer/PreviewGridItem.vue
  src/components/Composer/SubmitStatusButton.vue
  src/components/Composer/VisibilitySelect.vue
  src/components/Emoji.vue
  src/components/EmptyContent.vue
  src/components/FollowButton.vue
  src/components/MediaAttachment.vue
  src/components/MessageContent.js
  src/components/PostAttachment.vue
  src/components/ProfileInfo.vue
  src/components/Search.vue
  src/components/TimelineAvatar.vue
  src/components/TimelineEntry.vue
  src/components/TimelineList.vue
  src/components/TimelinePost.vue
  src/components/UserEntry.vue
  src/logger.js
  src/main.js
  src/mixins/accountMixins.js
  src/mixins/currentUserMixin.js
  src/mixins/follow.js
  src/mixins/popoverMenu.js
  src/mixins/serverData.js
  src/ostatus.js
  src/router.js
  src/store/account.js
  src/store/timeline.js
  src/types/ActivityPub.js
  src/types/Mastodon.js
  src/views/Dashboard.vue
  src/views/Profile.vue
  src/views/ProfileFollowers.vue
  src/views/Timeline.vue
  src/views/TimelineSinglePost.vue
  webpack.common.js
Labels: enhancement, 3. to review, javascript

#1647 Minor frontend fixes
  src/components/Composer/Composer.vue
  src/components/TimelineEntry.vue
Labels: bug, 2. developing

#1648 Use new API for favourite and reblog actions
  src/store/timeline.js
  src/types/Mastodon.js
Labels: bug, 3. to review, javascript

#1650 Fix typing for mention in MessageContent.js
  src/components/MessageContent.js
Labels: bug, 3. to review, javascript

#1641 strings(typo): fix a couple of issues
  .gitignore
  src/components/TimelineEntry.vue
Labels: 3. to review

#1660 Fix profile link at the top of statuses
  src/components/TimelineEntry.vue
  src/components/TimelinePost.vue
Labels: bug, 3. to review, javascript

#1665 Improve accessibility on statuses
  src/components/TimelineEntry.vue
  src/components/TimelinePost.vue
Labels: 3. to review, javascript

#1670 Use boost status in boost annoncements
  src/components/TimelineEntry.vue
Labels: bug, 3. to review, javascript

#1673 Use visibility of parent message when composing a reply
  src/components/Composer/Composer.vue
  src/components/Composer/SubmitStatusButton.vue
  src/components/Composer/VisibilitySelect.vue
Labels: enhancement, 3. to review, javascript

#1672 Fix mentions regexp to support '-' in domain names
  src/components/MessageContent.js
Labels: bug, 3. to review, javascript

#1671 Emphasis on beta state
  README.md
  appinfo/info.xml
  src/views/Timeline.vue
Labels: 3. to review

#1674 Add "open outside" icon for some link
  src/components/ProfileInfo.vue
Labels: enhancement, 3. to review, javascript

#1677 Improve attachments rendering
  src/components/Composer/Composer.vue
  src/components/PostAttachment.vue
  src/components/TimelinePost.vue
Labels: bug, 3. to review, javascript, front-end

#1676 Use primary color for reboost action
  src/components/TimelinePost.vue
Labels: bug, 3. to review, javascript, front-end

#1675 Add visibility on statuses
  package-lock.json
  package.json
  src/components/Composer/Composer.vue
  src/components/Composer/VisibilitySelect.vue
  src/components/TimelinePost.vue
  src/components/VisibilitiesInfos.js
  src/main.js
  src/views/Timeline.vue
Labels: enhancement, 3. to review, javascript, front-end

#1687 Automatically refetch timeline every 30sec
  src/components/TimelineList.vue
Labels: enhancement, 3. to review, javascript, front-end

#1686 Fix usage of NcAvatar in timeline statuses
  src/components/TimelineAvatar.vue
Labels: bug, 2. developing, javascript, front-end

#1692 Add composer in user profiles
  src/components/Composer/Composer.vue
  src/views/Profile.vue
Labels: enhancement, 3. to review, javascript, front-end

#1696 Show ancestors on single post timeline
  src/components/TimelineList.vue
  src/components/TimelinePost.vue
  src/router.js
  src/store/timeline.js
  src/types/Mastodon.js
  src/views/TimelineSinglePost.vue
Labels: enhancement, 3. to review, javascript, front-end

#1694 Set visibility as direct when on direct view
  src/views/Timeline.vue
Labels: bug, 3. to review, javascript, front-end

#1699 Display reply, favorites, and reblog counts
  src/components/TimelinePost.vue
Labels: enhancement, 3. to review, javascript, front-end
