Repository nextcloud/social, pull requests merged in 2024-09, with the labels that each got.

#1892 chore: migrate reuse to toml
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  src/App.vue
  src/dashboard.js
  src/main.js
  src/oauth.js
  src/ostatus.js
  src/profile.js
  src/router.js
Labels: 4. to release, technical debt

#1804 Updating cypress.yml workflow from template
  .github/workflows/cypress.yml
Labels: dependencies

#1904 chore: Update icons to latest Material Symbols
  LICENSES/Apache-2.0.txt
  LICENSES/LicenseRef-NextcloudTrademarks.txt
  REUSE.toml
  img/add_user.svg
  img/boost.svg
  img/emoji.svg
  img/notifications.svg
  img/reply.svg
  img/social-dark.svg
  img/social.svg
  img/social_dark.svg
Labels: 3. to review, design

#1910 Add npm audit fix
  .github/workflows/npm-audit-fix.yml
Labels: 4. to release, technical debt

#1878 Update npm and node engines versions
  package.json
Labels: dependencies, feedback-requested

#1914 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
